baseURL = 'https://tldrists.net'
title = 'TLDRists'
theme = 'tldrists'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en"
    [languages.en.params]
      description = "Your site description in English"
    [[languages.en.menu.main]]
      name = "Notae"
      url = "/notae/"
      weight = 1
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de"
    [languages.de.params]
      description = "Ihre Website-Beschreibung auf Deutsch"
    [[languages.de.menu.main]]
      name = "Notae"
      url = "/notae/"
      weight = 1
    [[languages.de.menu.main]]
      name = "Über uns"
      url = "/about/"
      weight = 2

[module]
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/lucide"

[menu]
  [[menu.main]]
    name = "Notae"
    url = "/notae/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
