name: Website

on:
  push:
    branches: [ main ]
    paths:
      - 'website/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version: ['0.148.2', 'latest']

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Build Hugo site
        run: hugo build --minify

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: website/public/
          format: text

  lighthouse-audit:
    runs-on: ubuntu-latest
    needs: build-test

    strategy:
      matrix:
        theme: ['light', 'dark']

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build site
        run: hugo build --minify --environment production --gc --cleanDestinationDir

      - name: Serve site
        run: |
          cd public
          serve -s . -l 8080 --cors &
          sleep 5

      - name: Audit site with Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:8080/
            http://localhost:8080/notae/
          configPath: website/.lighthouserc-${{ matrix.theme }}.json
          uploadArtifacts: false
          temporaryPublicStorage: true
